# Generated by Django 3.2.23 on 2023-12-15 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SensorData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.CharField(max_length=100)),
                ('oxygen', models.CharField(max_length=100)),
                ('temperature', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='Heart_beat',
        ),
        migrations.DeleteModel(
            name='Oxygen',
        ),
        migrations.DeleteModel(
            name='Temperature',
        ),
    ]
